flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/fros1y/patent-api
    commit: 41221b13cc6af0e809e6fe667aa35308d1f1e7b7
  extra-dep: true
# - location: ../patent-api/
#   extra-dep: true
extra-deps:
- wreq-0.5.0.0
resolver: lts-8.1
