flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:fros1y/patent-api.git
    commit: 014a3f3e15c630732b35d7fc687cc57bd1aa0497
  extra-dep: true
# - location: ../patent-api/
#   extra-dep: true
extra-deps:
- wreq-0.5.0.0
resolver: lts-8.1
