flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:fros1y/patent-api.git
    commit: 3c0cfff81968acf6499a4e43974fb12fcd74483d
  extra-dep: true
# - location: ../patent-api/
#   extra-dep: true
extra-deps:
- wreq-0.5.0.0
resolver: lts-8.1
